export const AVAILABLE_MOVIE_TITLES: string[] = [
    "The Lord of the Rings: The Return of the King",
    "The Pianist",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "Oldboy",
    "Pan's Labyrinth",
    "The Dark Knight",
    "The King's Speech",
    "Children of Men",
    "The Departed",
    "Amour",
    "Gravity",
    "Shaun of the Dead",
    "A Beautiful Mind",
    "Downfall",
    "Inception",
    "Cold Mountain",
    "In the Loop",
    "Letters from Iwo Jima",
    "Gangs of New York",
    "Beasts of the Southern Wild",
    "Road to Perdition",
    "Sideways",
    "King Kong",
    "The Reader",
    "The Dark Knight Rises",
    "Brokeback Mountain",
    "Les Misérables",
    "Public Enemies",
    "Gladiator",
    "The Incredibles",
    "Unbreakable",
    "Batman Begins",
    "Before Night Falls",
    "Milk",
    "Blue Valentine",
    "Shutter Island",
    "The Artist",
    "Departures",
    "Lawless"
]